// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSmTsaDFh-OF_Gr3ql9nD43gheWUD76Mo',
    appId: '1:512980028270:web:360ee8756556c789eb4f7f',
    messagingSenderId: '512980028270',
    projectId: 'fincontrol-6b7c9',
    authDomain: 'fincontrol-6b7c9.firebaseapp.com',
    storageBucket: 'fincontrol-6b7c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCToHoZX1DHAA7cXWoqEMnyiRvVmQGEuu4',
    appId: '1:512980028270:android:4cc5aebd8c540e91eb4f7f',
    messagingSenderId: '512980028270',
    projectId: 'fincontrol-6b7c9',
    storageBucket: 'fincontrol-6b7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1yUU2dS3BusruQPFpSNwwbyOTNfONSEA',
    appId: '1:512980028270:ios:52767868de630538eb4f7f',
    messagingSenderId: '512980028270',
    projectId: 'fincontrol-6b7c9',
    storageBucket: 'fincontrol-6b7c9.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1yUU2dS3BusruQPFpSNwwbyOTNfONSEA',
    appId: '1:512980028270:ios:52767868de630538eb4f7f',
    messagingSenderId: '512980028270',
    projectId: 'fincontrol-6b7c9',
    storageBucket: 'fincontrol-6b7c9.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSmTsaDFh-OF_Gr3ql9nD43gheWUD76Mo',
    appId: '1:512980028270:web:543b087cdf5fdaa5eb4f7f',
    messagingSenderId: '512980028270',
    projectId: 'fincontrol-6b7c9',
    authDomain: 'fincontrol-6b7c9.firebaseapp.com',
    storageBucket: 'fincontrol-6b7c9.firebasestorage.app',
  );
}
